server:
  port: 8088
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/debit
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost  
